### ISSUE TITLE
Agents types description in Library

### ISSUE THREAD

**Issue by KaatjeEns** [AMS-CSL/CSL_Model#2]
Hi, 
For me, you describe two agent types, " inhabitants" and "peers" of which you see peers as a subset of inhabitants.
This is not correct in my opinion. All agents will belong to one type of agent e.g. inhabitant, tourist, while at the same time they are each others peers. But peer  is not an agent type ansich

**Comment by bsrirama** [comment]
It is same as how you describe it :)
